### ISSUE TITLE
guards do not allow function calls

### ISSUE THREAD

**Issue by disnet** [natefaubion/sparkler#10]
``` js
function foo {
    x @ Number if isPos(b) => 100
}
```

Throws:

```
Warning: Cannot read property 'constructor' of undefined Use --force to continue.
TypeError: Cannot read property 'constructor' of undefined
    at cloneSyntax$541 (eval at <anonymous> (/Users/tim/Dropbox/dev/sweet-virtual-values/node_modules/sweet.js/lib/scopedEval.js:16:69), <anonymous>:230:76)
```

Is this a sparkler or a sweet.js bug?

**Comment by natefaubion** [comment]
https://github.com/natefaubion/sparkler/blob/master/src/utils.js#L223-L232

It's a sparkler bug, but we need to expose syntax cloning as a method on syntax objects.

**Comment by natefaubion** [comment]
Fixed with https://github.com/natefaubion/sparkler/commit/5356009cf020add95cb9bcfd54bfc617357fe390
